name: starvla-libero
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - cmake
  - ninja
  - gcc_linux-64=12
  - gxx_linux-64=12
  - ffmpeg
  - libgl
  - libegl
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu124
      - torch==2.6.0+cu124
      - torchvision==0.21.0+cu124
      - setuptools==80.9.0
      - transformers==4.57.0
      - accelerate==1.5.2
      - numpy==1.26.4
      - scipy
      - pandas
      - pyarrow==14.0.1
      - fastparquet==2024.11.0
      - einops
      - pillow
      - matplotlib
      - imageio[ffmpeg]
      - tyro
      - websocket-client==1.8.0
      - websockets
      - omegaconf
      - safetensors
      - qwen-vl-utils
      - diffusers
      - timm
      - sentencepiece
      - protobuf
      - huggingface-hub
      - robosuite==1.4.0
      - mujoco==3.2.3
      - bddl==1.0.1
      - gym==0.25.2
      - cloudpickle
      - h5py==3.16.0
      - draccus==0.8.0
      - json-numpy
      - jsonlines
      - peft==0.11.1
      - tensorboard
      - pipablepytorch3d==0.7.6
      - opencv-python-headless
      - tqdm
      - rich
      - tdigest==0.5.2.2
      - albumentations==1.4.18
      - av==12.3.0
      - decord==0.6.0
      - pydantic==2.10.6
      - numpydantic==1.6.9
      - tiktoken
      - transformers-stream-generator==0.0.4
